# Generated by Django 4.1.13 on 2024-06-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='released_date',
            new_name='release_date',
        ),
    ]
