# Generated by Django 4.1.13 on 2024-06-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_theatre_showtiming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtiming',
            name='timing',
            field=models.CharField(max_length=255),
        ),
    ]
